спринт 10: работа с веткой add-friends-likes
vitaliibredun/java-filmorate pull request #2
Opened 2022-12-05 14:54 UTC by vitaliibredun

2022-12-06 12:21 UTC, ErkinKasymaliev requested changes
Здравствуйте, хорошая работа, только надо обратить внимание на 1 коммент, может я вашу задумку не так понял.
Также у вас не проходят тесты (вкладка Checks), а это обязательно, к следующей итерации это надо починить. Спросите у наставника об этом.

2022-12-06 12:21 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +public class FilmValidation extends InMemoryFilmStorage {
не совсем понимаю зачем вы наследуете здесь? FilmValidation может работать вполне отдельно, как и UserValidation

2022-12-06 13:52 UTC, vitaliibredun commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +public class FilmValidation extends InMemoryFilmStorage {
к сожалению не придумал лаконичного решения нормального)
в обоих классах наследуюсь от storage только ради проверки id user/film, на случай когда такого id не существует в памяти

if (!films.containsKey(film.getId())) {
            if (!films.isEmpty()) {
                if (film.getId() != 0) {
                    log.error("Validation failed. The film with the id doesn't exist {}", film.getId());
                    throw new FilmNotFoundException("Фильма с таким id не существует");
                }
            }
        }
        
        if (!users.containsKey(user.getId()))
            if (!users.isEmpty()) {
                if (user.getId() != 0) {
                    log.error("Validation failed. The user with the id doesn't exist {}", user.getId());
                    throw new UserNotFoundException("Пользователя с таким id не существует");
                }
            }
        }

2022-12-06 13:56 UTC, vitaliibredun commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +public class FilmValidation extends InMemoryFilmStorage {
по поводу теста, возможно знаю причину, сейчас попробую перезалить

2022-12-06 14:04 UTC, vitaliibredun commented on src/main/java/ru/yandex/practicum/filmorate/validation/FilmValidation.java
> +public class FilmValidation extends InMemoryFilmStorage {
> по поводу теста, возможно знаю причину, сейчас попробую перезалить

тут перезалил, починил)

2022-12-09 19:50 UTC, ErkinKasymaliev requested changes
Привет, оставил 1 коммент

2022-12-09 19:50 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/checking/FilmCheck.java
> +public class FilmCheck {
Здесь я с вами не соглашусь, так как это класс уже избыточный. Все проверки можно и в FilmService сделать.
Аналогично для UserCheck.

2022-12-09 20:02 UTC, vitaliibredun commented on src/main/java/ru/yandex/practicum/filmorate/service/checking/FilmCheck.java
> +public class FilmCheck {
не спорю, не знал куда лучше проверки перенести. У меня просто по сути есть сервисный класс и классы вариации(где есть реализация необходимых проверок) но в тоже время у меня в сервисных классах есть дополнительные проверки которые мешают понимать код, хочу их перенести в один класс, что сервисные классы отвечали за обработку запросов а проверка и возвожые обработки исключений в отдельном соответственно классе.

Может методы из классов FilmCheck и UserCheck перенесу в классы валидации?(FilmValodation и UserValidation) 

так у меня будет реализация при которой есть сервисные классы и есть классы отвечающие за проверку на валидность и обработку исключений

2022-12-11 16:44 UTC, ErkinKasymaliev approved these changes
Отлично, поправили как и договаривались, работа принята!

2022-12-11 16:44 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/checking/FilmCheck.java
> +public class FilmCheck {
все эти проверки можете реализовать в хранилище. Смотрите jdbc.query() и jdbc.update() возвращают число строк. Если результат будет 0, то можете кидать любое из исключений ниже

2022-12-11 17:15 UTC, vitaliibredun commented on src/main/java/ru/yandex/practicum/filmorate/service/checking/FilmCheck.java
> +public class FilmCheck {
спасибо

2022-12-11 17:16 UTC, merged